### PR TITLE
Directory restructure

### PR DESCRIPTION
**Pull request by vrutkovs**
To make Lightread a distro-agnostic application current directory structure should be revised. Here are some points which are requried to have Lightread in other distribution e.g. Fedora:
- Don't place files in /opt
- Use setup.py
- Don't use Ubuntu folder

### CODE REVIEW

**Comment by consindo** [comment]
I don't think I can do this. The software center requires opt and the ubuntu folder

**Comment by vrutkovs** [comment]
These requirements are for extras repository only. If Lightread is planned to hit multiverse repo (and other Ubuntu repos) it should comply with Filesystem Hierarchy Standard, which restrict user files to be placed in /opt (see http://www.pathname.com/fhs/pub/fhs-2.3.html#SRVDATAFORSERVICESPROVIDEDBYSYSTEM)

So if Lightread is planned to be used in other distributions (or in core Ubuntu repos), file hierarchy should be changed

**Comment by nagisa** [comment]
Running `sh compile.sh; and cd Ubuntu; and python2 setup.py install --prefix=install_dir/usr/` installs everything into a very [clean tree](https://gist.github.com/291e6511ab143b9ce230) which can be used on any linux disto I can think of.

**Comment by vrutkovs** [comment]
@simukis it does, yet lightread is not runnable, as /opt/extras.ubuntu.com is hardcoded and interferes with python path

**Comment by vrutkovs** [comment]
Sorry, seems that local build and install work correctly now

**Pull request closed without merging**
